<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DocMgr.Tools.SimulatedMediaRegisterVerify</RootNamespace>
    <AssemblyName>SimulatedMediaRegisterVerify</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DocMgr.csproj" />
  </ItemGroup>

</Project>
