using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;
using DocMgr.ViewModels.SystemSettings;
using Microsoft.Extensions.DependencyInjection;

namespace DocMgr.Views.SystemSettings
{
    public partial class AdvancedDataPage : Page
    {
        private readonly IServiceScope _pageScope;

        public AdvancedDataPage()
        {
            InitializeComponent();

            _pageScope = App.CurrentProvider.CreateScope();
            DataContext = _pageScope.ServiceProvider.GetRequiredService<AdvancedDataPageViewModel>();

            if (DataContext is AdvancedDataPageViewModel vm)
            {
                vm.PropertyChanged += ViewModel_PropertyChanged;
            }

            Unloaded += AdvancedDataPage_Unloaded;
        }

        private void RecordsDataGrid_OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            ApplyColumnHeaderAndMinWidth(e.Column, e.PropertyName);
        }

        private void RecordsDataGrid_OnAutoGeneratedColumns(object? sender, EventArgs e)
        {
            UpdateColumnHeaders();
            // 换表/重建列后回到最左，避免沿用上一张表的水平偏移造成“缺列”错觉
            ScheduleScrollExtentRefresh(resetHorizontalOffset: true);
        }

        private void ViewModel_PropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(AdvancedDataPageViewModel.TableFields))
            {
                UpdateColumnHeaders();
                ScheduleScrollExtentRefresh(resetHorizontalOffset: false);
            }
            else if (e.PropertyName == nameof(AdvancedDataPageViewModel.RecordsView))
            {
                // 翻页只换行数据，列集合不变：刷新量度但不强制回滚水平位置
                ScheduleScrollExtentRefresh(resetHorizontalOffset: false);
            }
        }

        private void UpdateColumnHeaders()
        {
            foreach (var column in RecordsDataGrid.Columns)
            {
                var fieldName = column.SortMemberPath;
                if (string.IsNullOrWhiteSpace(fieldName) && column.Header is string headerText)
                {
                    fieldName = headerText;
                }

                if (!string.IsNullOrWhiteSpace(fieldName))
                {
                    ApplyColumnHeaderAndMinWidth(column, fieldName);
                }
            }
        }

        private void ApplyColumnHeaderAndMinWidth(DataGridColumn column, string fieldName)
        {
            var alias = ResolveFieldAlias(fieldName);
            column.Header = CreateColumnHeader(fieldName, alias);
            column.MinWidth = Math.Max(96, MeasureHeaderPairWidth(fieldName, alias) + 24);
        }

        private string ResolveFieldAlias(string fieldName)
        {
            if (DataContext is not AdvancedDataPageViewModel vm)
            {
                return fieldName;
            }

            var alias = vm.TableFields
                .FirstOrDefault(field => string.Equals(field.FieldName, fieldName, StringComparison.OrdinalIgnoreCase))
                ?.DisplayName;

            return string.IsNullOrWhiteSpace(alias) ? fieldName : alias;
        }

        /// <summary>
        /// 双行表头：英文字段名 + 中文别名。
        /// 必须按内容量度（Center + NoWrap），禁止 Stretch/Wrap，否则 SizeToHeader 会按可用宽度压缩列，
        /// 总宽被压进视口后水平滚动条不出现，末列看起来像被截断。
        /// </summary>
        private static UIElement CreateColumnHeader(string fieldName, string alias)
        {
            var aliasBrush = new SolidColorBrush(Color.FromRgb(0xD7, 0xF0, 0xEC));

            return new StackPanel
            {
                Orientation = Orientation.Vertical,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(0, 2, 0, 2),
                Children =
                {
                    new TextBlock
                    {
                        Text = fieldName,
                        FontSize = 13,
                        FontWeight = FontWeights.SemiBold,
                        HorizontalAlignment = HorizontalAlignment.Center,
                        TextAlignment = TextAlignment.Center,
                        TextWrapping = TextWrapping.NoWrap,
                        LineHeight = 18,
                        LineStackingStrategy = LineStackingStrategy.BlockLineHeight
                    },
                    new TextBlock
                    {
                        Text = alias,
                        FontSize = 11,
                        FontWeight = FontWeights.Normal,
                        Foreground = aliasBrush,
                        HorizontalAlignment = HorizontalAlignment.Center,
                        TextAlignment = TextAlignment.Center,
                        TextWrapping = TextWrapping.NoWrap,
                        LineHeight = 16,
                        LineStackingStrategy = LineStackingStrategy.BlockLineHeight,
                        Margin = new Thickness(0, 2, 0, 0)
                    }
                }
            };
        }

        private static double MeasureHeaderPairWidth(string fieldName, string alias)
        {
            return Math.Max(
                MeasureTextWidth(fieldName, fontSize: 13, FontWeights.SemiBold),
                MeasureTextWidth(alias, fontSize: 11, FontWeights.Normal));
        }

        private static double MeasureTextWidth(string text, double fontSize, FontWeight fontWeight)
        {
            var textBlock = new TextBlock
            {
                Text = text,
                FontSize = fontSize,
                FontWeight = fontWeight,
                TextWrapping = TextWrapping.NoWrap
            };
            textBlock.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            return textBlock.DesiredSize.Width;
        }

        /// <summary>
        /// 异步换 DataView / 重建列后，强制刷新内部 ScrollViewer 量度，避免 ExtentWidth 残留低估。
        /// </summary>
        private void ScheduleScrollExtentRefresh(bool resetHorizontalOffset)
        {
            Dispatcher.BeginInvoke(
                DispatcherPriority.Loaded,
                () => RefreshScrollExtent(resetHorizontalOffset));
        }

        private void RefreshScrollExtent(bool resetHorizontalOffset)
        {
            if (!IsLoaded)
            {
                return;
            }

            RecordsDataGrid.UpdateLayout();
            var scrollViewer = FindVisualChild<ScrollViewer>(RecordsDataGrid);
            if (scrollViewer == null)
            {
                return;
            }

            scrollViewer.InvalidateMeasure();
            scrollViewer.InvalidateArrange();
            scrollViewer.UpdateLayout();

            if (resetHorizontalOffset && scrollViewer.HorizontalOffset > 0)
            {
                scrollViewer.ScrollToHorizontalOffset(0);
            }
        }

        private static T? FindVisualChild<T>(DependencyObject parent) where T : DependencyObject
        {
            for (var i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
            {
                var child = VisualTreeHelper.GetChild(parent, i);
                if (child is T typed)
                {
                    return typed;
                }

                var nested = FindVisualChild<T>(child);
                if (nested != null)
                {
                    return nested;
                }
            }

            return null;
        }

        private void AdvancedDataPage_Unloaded(object sender, RoutedEventArgs e)
        {
            Unloaded -= AdvancedDataPage_Unloaded;

            if (DataContext is AdvancedDataPageViewModel vm)
            {
                vm.PropertyChanged -= ViewModel_PropertyChanged;
                vm.MarkDisposed();
            }

            DataContext = null;
            _pageScope.Dispose();
        }
    }
}
