using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using DocMgr.ViewModels.SystemSettings;
using Microsoft.Extensions.DependencyInjection;

namespace DocMgr.Views.SystemSettings
{
    public partial class AdvancedDataPage : Page
    {
        private readonly IServiceScope _pageScope;

        public AdvancedDataPage()
        {
            InitializeComponent();

            _pageScope = App.CurrentProvider.CreateScope();
            DataContext = _pageScope.ServiceProvider.GetRequiredService<AdvancedDataPageViewModel>();

            if (DataContext is AdvancedDataPageViewModel vm)
            {
                vm.PropertyChanged += ViewModel_PropertyChanged;
            }

            Unloaded += AdvancedDataPage_Unloaded;
        }

        private void RecordsDataGrid_OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            ApplyColumnHeader(e.Column, e.PropertyName);
        }

        private void RecordsDataGrid_OnAutoGeneratedColumns(object? sender, EventArgs e)
        {
            UpdateColumnHeaders();
        }

        private void ViewModel_PropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(AdvancedDataPageViewModel.TableFields)
                || e.PropertyName == nameof(AdvancedDataPageViewModel.RecordsView))
            {
                UpdateColumnHeaders();
            }
        }

        private void UpdateColumnHeaders()
        {
            foreach (var column in RecordsDataGrid.Columns)
            {
                var fieldName = column.SortMemberPath;
                if (string.IsNullOrWhiteSpace(fieldName) && column.Header is string headerText)
                {
                    fieldName = headerText;
                }

                if (!string.IsNullOrWhiteSpace(fieldName))
                {
                    ApplyColumnHeader(column, fieldName);
                }
            }
        }

        private void ApplyColumnHeader(DataGridColumn column, string fieldName)
        {
            var alias = ResolveFieldAlias(fieldName);
            column.Header = CreateColumnHeader(fieldName, alias);
        }

        private string ResolveFieldAlias(string fieldName)
        {
            if (DataContext is not AdvancedDataPageViewModel vm)
            {
                return fieldName;
            }

            var alias = vm.TableFields
                .FirstOrDefault(field => string.Equals(field.FieldName, fieldName, StringComparison.OrdinalIgnoreCase))
                ?.DisplayName;

            return string.IsNullOrWhiteSpace(alias) ? fieldName : alias;
        }

        private static UIElement CreateColumnHeader(string fieldName, string alias)
        {
            var aliasBrush = new SolidColorBrush(Color.FromRgb(0xD7, 0xF0, 0xEC));

            return new StackPanel
            {
                Orientation = Orientation.Vertical,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(0, 2, 0, 2),
                Children =
                {
                    new TextBlock
                    {
                        Text = fieldName,
                        FontSize = 13,
                        FontWeight = FontWeights.SemiBold,
                        HorizontalAlignment = HorizontalAlignment.Center,
                        TextAlignment = TextAlignment.Center,
                        LineHeight = 18,
                        LineStackingStrategy = LineStackingStrategy.BlockLineHeight
                    },
                    new TextBlock
                    {
                        Text = alias,
                        FontSize = 11,
                        FontWeight = FontWeights.Normal,
                        Foreground = aliasBrush,
                        HorizontalAlignment = HorizontalAlignment.Center,
                        TextAlignment = TextAlignment.Center,
                        TextWrapping = TextWrapping.Wrap,
                        LineHeight = 16,
                        LineStackingStrategy = LineStackingStrategy.BlockLineHeight,
                        Margin = new Thickness(0, 2, 0, 0)
                    }
                }
            };
        }

        private void AdvancedDataPage_Unloaded(object sender, RoutedEventArgs e)
        {
            Unloaded -= AdvancedDataPage_Unloaded;

            if (DataContext is AdvancedDataPageViewModel vm)
            {
                vm.PropertyChanged -= ViewModel_PropertyChanged;
                vm.MarkDisposed();
            }

            DataContext = null;
            _pageScope.Dispose();
        }
    }
}
